import { useEffect, useRef, useState, type ChangeEvent, type FormEvent, type ReactNode } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';
import { Route, Switch, useLocation, Router as WouterRouter, Link } from 'wouter';
import { BookOpen, Network, Brain, ChartNoAxesColumnIncreasing, Settings, Home, Plus, ArrowLeft, ArrowUpLeft, ArrowDownToLine, Upload, Trash2, Pencil, X, FileText, Check, ChevronLeft, Sun, Moon, Sparkles, CircleHelp, ShieldCheck, RotateCcw, Save, Link2, CircleCheck, AlertCircle } from 'lucide-react';

type Source = { id:string; title:string; type:string; content:string; createdAt:string };
type Concept = { id:string; title:string; description:string; sourceId:string; sourceLocation:string; status:string };
type Relation = { id:string; fromConceptId:string; toConceptId:string; label:string; confidence:number; reviewStatus:string };
type Question = { id:string; prompt:string; choices:string[]; correctChoice:number; conceptId:string; sourceId:string; sourceLocation:string };
type Evidence = { id:string; questionId:string; conceptId:string; selectedChoice:number; correct:boolean; confidence:number; assisted:false; createdAt:string };
type StudyMode = { id:string; name:string; questionCount:number; allowHints:boolean };
type Store = { schema:number; sources:Source[]; concepts:Concept[]; relations:Relation[]; questions:Question[]; evidence:Evidence[]; modes:StudyMode[]; sample:boolean };
const STORAGE_KEY = 'itqan-workspace-v1';
const id = () => `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const seed:Store = {
  schema:1,sample:true,
  sources:[{id:'s-water',title:'دورة الماء في الطبيعة',type:'ملاحظات درس',content:'تسخّن الشمس مياه البحار والمحيطات، فيتحول جزء منها إلى بخار ماء يصعد إلى الجو. عندما يبرد البخار يتكاثف مكوّناً السحب، ثم يعود الماء إلى الأرض على هيئة مطر أو ثلج. وتسمى هذه الحركة المستمرة دورة الماء.',createdAt:new Date().toISOString()},{id:'s-memory',title:'مبادئ التعلّم والاسترجاع',type:'ملخص شخصي',content:'يساعد الاسترجاع النشط على تقوية الروابط في الذاكرة. محاولة تذكّر المعلومة قبل الرجوع إلى المصدر تكشف ما نعرفه وما يحتاج إلى مراجعة.',createdAt:new Date().toISOString()}],
  concepts:[{id:'c-evap',title:'التبخر',description:'تحول الماء السائل إلى بخار بفعل الحرارة.',sourceId:'s-water',sourceLocation:'السطر 1',status:'مراجعتي الأولى'},{id:'c-cond',title:'التكاثف',description:'تبريد بخار الماء وتحوله إلى قطرات تكوّن السحب.',sourceId:'s-water',sourceLocation:'السطر 2',status:'قيد المراجعة'},{id:'c-recall',title:'الاسترجاع النشط',description:'محاولة استحضار المعرفة من الذاكرة قبل الاطلاع على المصدر.',sourceId:'s-memory',sourceLocation:'السطر 1',status:'مراجعتي الأولى'}],
  relations:[{id:'r1',fromConceptId:'c-evap',toConceptId:'c-cond',label:'يسبق في الدورة',confidence:72,reviewStatus:'بحاجة للمراجعة'}],
  questions:[{id:'q1',prompt:'ما الذي يحدث لبخار الماء عندما يبرد في الجو؟',choices:['يتكاثف مكوّناً السحب','يتحول مباشرة إلى تربة','يختفي من دورة الماء'],correctChoice:0,conceptId:'c-cond',sourceId:'s-water',sourceLocation:'السطر 2'},{id:'q2',prompt:'متى تكون محاولة الاسترجاع أكثر فائدة؟',choices:['بعد قراءة الإجابة مباشرة','قبل الرجوع إلى المصدر','عند نسخ التعريف فقط'],correctChoice:1,conceptId:'c-recall',sourceId:'s-memory',sourceLocation:'السطر 2'}],
  evidence:[],modes:[{id:'mode-gentle',name:'جلسة هادئة',questionCount:3,allowHints:false},{id:'mode-focus',name:'تركيز قصير',questionCount:5,allowHints:false}]
};
function safeStore():Store {
  try { const raw=localStorage.getItem(STORAGE_KEY); if(!raw)return seed; const x=JSON.parse(raw); if(x?.schema===1&&Array.isArray(x.sources)&&Array.isArray(x.concepts)&&Array.isArray(x.relations)&&Array.isArray(x.questions)&&Array.isArray(x.evidence)&&Array.isArray(x.modes)) return {...seed,...x}; } catch { /* corrupted local data uses a safe starter dataset */ }
  return seed;
}
const queryClient = new QueryClient();
const navItems = [
  {href:'/',label:'اليوم',Icon:Home},
  {href:'/sources',label:'مصادري',Icon:BookOpen},
  {href:'/knowledge',label:'خريطة المعرفة',Icon:Network},
  {href:'/study',label:'تدرّب',Icon:Brain},
  {href:'/progress',label:'أثر التعلّم',Icon:ChartNoAxesColumnIncreasing},
  {href:'/settings',label:'الإعدادات',Icon:Settings}
];
const titles:Record<string,string>={'/':'مساحة اليوم','/sources':'مصادري','/knowledge':'خريطة المعرفة','/study':'جلسة الاسترجاع','/progress':'أثر التعلّم','/settings':'إعدادات مساحتك'};
function AppShell({children, page, dark, toggleTheme, store}:{children:ReactNode;page:string;dark:boolean;toggleTheme:()=>void;store:Store}) {
  const nav=(mobile=false)=><nav aria-label="التنقل الرئيسي" className={mobile?'mobile-nav':'nav-group'}>{navItems.map(({href,label,Icon})=><Link key={href} href={href} data-testid={`nav-${href==='/ ' ? 'home' : href==='/'?'today':href.slice(1)}`} className={`nav-link ${page===href?'active':''}`} aria-current={page===href?'page':undefined}><Icon size={18}/><span className="nav-label">{label}</span></Link>)}</nav>;
  return <div className="app-shell" dir="rtl">
    <aside className="sidebar"><Link href="/" className="brand" data-testid="link-brand"><span className="brand-mark">إ</span><span><span className="brand-name">إتقان</span><span className="brand-sub">LEARN, IN YOUR OWN WORDS</span></span></Link>{nav()}<div className="side-bottom"><span className="storage-dot"/> بياناتك محفوظة على هذا الجهاز<br/><span style={{fontSize:10}}>مساحة شخصية، بلا حساب أو مزامنة سحابية.</span></div></aside>
    <main className="main-area"><header className="topbar"><span className="crumb">مساحتك الشخصية <span style={{opacity:.5}}> / </span> {titles[page]||'إتقان'}</span><div className="top-actions"><span className="date-label">{new Intl.DateTimeFormat('ar', {weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span><button type="button" className="top-icon" onClick={toggleTheme} aria-label={dark?'تفعيل الوضع الفاتح':'تفعيل الوضع الداكن'} data-testid="toggle-theme">{dark?<Sun size={16}/>:<Moon size={16}/>}</button></div></header>{children}</main>{nav(true)}
  </div>;
}
function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1 className="page-title">{title}</h1><p className="page-desc">{description}</p></div>{action}</div>}
function SampleNote(){return <div className="sample-note" data-testid="status-sample-content"><Sparkles size={15}/><span><b>محتوى تجريبي قابل للتحرير</b> — غيّره أو احذفه وابدأ بمصادرك الخاصة.</span></div>}
function Empty({title,copy,icon:Icon=BookOpen}:{title:string;copy:string;icon?:typeof BookOpen}){return <div className="card empty-state" data-testid="empty-state"><div className="empty-mark"><Icon size={21}/></div><b style={{display:'block',color:'hsl(var(--foreground))',marginBottom:7}}>{title}</b><span style={{fontSize:12,lineHeight:1.8}}>{copy}</span></div>}

function WorkspaceApp() {
  const [location,setLocation]=useLocation();
  const [store,setStore]=useState<Store>(()=>safeStore());
  const [dark,setDark]=useState(()=>localStorage.getItem('itqan-theme')==='dark');
  useEffect(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(store));},[store]);
  useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('itqan-theme',dark?'dark':'light');},[dark]);
  const [notice,setNotice]=useState('');
  const flash=(s:string)=>{setNotice(s);window.setTimeout(()=>setNotice(''),3200)};
  const patch=(key:keyof Store, value:unknown)=>setStore(s=>({...s,[key]:value,sample:s.sample} as Store));
  const dropSample=()=>setStore(s=>({...s,sample:false}));
  const removeSource=(sid:string)=>{if(!window.confirm('حذف هذا المصدر؟ سيُحذف معه المفاهيم والأسئلة والروابط المرتبطة به.'))return;setStore(s=>({...s,sources:s.sources.filter(x=>x.id!==sid),concepts:s.concepts.filter(x=>x.sourceId!==sid),questions:s.questions.filter(x=>x.sourceId!==sid),relations:s.relations.filter(r=>s.concepts.find(c=>c.id===r.fromConceptId)?.sourceId!==sid&&s.concepts.find(c=>c.id===r.toConceptId)?.sourceId!==sid),evidence:s.evidence.filter(e=>s.questions.find(q=>q.id===e.questionId)?.sourceId!==sid),sample:false}));flash('تم حذف المصدر والعناصر المرتبطة به');};
  const page=location;
  return <QueryClientProvider client={queryClient}><TooltipProvider><ErrorBoundary resetKey={location}><AppShell page={page} dark={dark} toggleTheme={()=>setDark(v=>!v)} store={store}>
    {notice&&<div role="status" className="toast-message" data-testid="status-action-result"><CircleCheck size={15}/>{notice}</div>}
    <Switch>
      <Route path="/"><HomePage store={store}/></Route>
      <Route path="/sources"><SourcesPage store={store} patch={patch} dropSample={dropSample} removeSource={removeSource}/></Route>
      <Route path="/knowledge"><KnowledgePage store={store} patch={patch} dropSample={dropSample}/></Route>
      <Route path="/study"><StudyPage store={store} patch={patch} dropSample={dropSample}/></Route>
      <Route path="/progress"><ProgressPage store={store} patch={patch}/></Route>
      <Route path="/settings"><SettingsPage store={store} patch={patch} onReset={()=>{if(window.confirm('سيُحذف كل ما حفظته على هذا الجهاز. هل تريد المتابعة؟')){setStore({...seed,evidence:[],sample:true});flash('تمت إعادة المساحة إلى محتواها الأولي');}}} dark={dark} toggleTheme={()=>setDark(v=>!v)} flash={flash}/></Route>
      <Route component={NotFound}/>
    </Switch>
  </AppShell></ErrorBoundary><Toaster/></TooltipProvider></QueryClientProvider>;
}

function HomePage({store}:{store:Store}) {
  const nextQuestion=store.questions.find(q=>!store.evidence.some(e=>e.questionId===q.id))||store.questions[0];
  const srcCount=store.sources.length,conceptCount=store.concepts.length,practiceCount=store.evidence.length;
  return <div className="content"><PageHeading eyebrow="YOUR OWN LEARNING SPACE" title="أهلًا بك في إتقان" description="تعلّم من مصادرك، واختبر ما تتذكره، وراقب الدليل بهدوء."/>
    {store.sample&&<SampleNote/>}
    <section className="home-hero" data-testid="panel-today"><div className="hero-copy"><span className="hero-kicker">A MOMENT FOR YOURSELF</span><h2 className="hero-title">المعرفة التي تسترجعها،<br/>تصبح أقرب إليك.</h2><p className="hero-sub">جلسة قصيرة من مصادرك أنت. لا إجابات جاهزة، فقط مساحة لتفكر.</p><Link href="/study" className="button button-secondary" data-testid="button-start-study">ابدأ جلسة استرجاع <ArrowLeft size={15}/></Link></div><div className="hero-art" aria-hidden="true"><div className="orbit"/><div className="orbit"/><div className="orbit-dot"/><div className="hero-core">إ</div></div></section>
    <div className="section-head"><h2 className="section-title">خطوتك التالية</h2><span className="eyebrow">ONE SMALL STEP</span></div>
    <div className="next-grid"><Link href={nextQuestion?'/study':'/sources'} className="card action-card" style={{textDecoration:'none',color:'inherit'}} data-testid="card-next-action"><span className="action-icon"><Brain size={21}/></span><span className="row-main"><span className="action-title">{nextQuestion?'استرجع مفهومًا من ذاكرتك':'أضف أول مصدر تتعلم منه'}</span><span className="action-caption">{nextQuestion?`سؤال من «${store.sources.find(s=>s.id===nextQuestion.sourceId)?.title||'مصادرك'}» — دون مساعدة.`:'النصوص التي تثق بها هي نقطة البداية.'}</span></span><ChevronLeft size={18}/></Link>
      <div className="card action-card"><span className="action-icon"><ShieldCheck size={21}/></span><span><span className="action-title">قرارك يبقى لك</span><span className="action-caption">لا مساعدات ذكية أثناء التقييم. إجابتك لك وحدك.</span></span></div></div>
    <div className="stats-strip" aria-label="ملخص المساحة"><div className="stat-cell"><div><div className="stat-num" data-testid="value-source-count">{srcCount}</div><div className="stat-label">مصدر شخصي</div></div><BookOpen size={17}/></div><div className="stat-cell"><div><div className="stat-num" data-testid="value-concept-count">{conceptCount}</div><div className="stat-label">مفهوم مرتبط بمصدر</div></div><Network size={17}/></div><div className="stat-cell"><div><div className="stat-num" data-testid="value-evidence-count">{practiceCount}</div><div className="stat-label">استجابة محفوظة كدليل</div></div><ChartNoAxesColumnIncreasing size={17}/></div></div>
    <div className="section-head"><h2 className="section-title">من ملاحظاتك</h2><Link href="/sources" className="text-link" data-testid="link-all-sources">عرض المصادر <ArrowUpLeft size={13}/></Link></div>
    {store.sources.length?<div className="list-stack">{store.sources.slice(0,2).map(s=><div className="card source-row" key={s.id}><div className="row-icon"><FileText size={18}/></div><div className="row-main"><div className="row-title">{s.title}</div><div className="row-meta"><span>{s.type}</span><span>{store.concepts.filter(c=>c.sourceId===s.id).length} مفاهيم</span></div></div></div>)}</div>:<Empty title="ابدأ بمصدر واحد" copy="أضف ملاحظاتك أو ملخصًا لتنشئ مساحة تعلم تستند إلى ما تثق به."/>}
  </div>;
}

function SourcesPage({store,patch,dropSample,removeSource}:{store:Store;patch:(k:keyof Store,v:unknown)=>void;dropSample:()=>void;removeSource:(id:string)=>void}) {
  const [editing,setEditing]=useState<Source|null>(null),[creating,setCreating]=useState(false),[query,setQuery]=useState('');
  const save=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),title=String(f.get('title')).trim(),content=String(f.get('content')).trim(),type=String(f.get('type')).trim()||'ملاحظات';if(!title||!content)return;const item:Source={id:editing?.id||id(),title,content,type,createdAt:editing?.createdAt||new Date().toISOString()};patch('sources',editing?store.sources.map(s=>s.id===editing.id?item:s):[item,...store.sources]);dropSample();setEditing(null);setCreating(false);};
  const filtered=store.sources.filter(s=>`${s.title} ${s.content} ${s.type}`.includes(query));
  const form=(item:Source|null)=><form className="card form-card" onSubmit={save} data-testid="form-source"><div className="form-grid"><div className="field"><label htmlFor="source-title">عنوان المصدر</label><input id="source-title" name="title" required defaultValue={item?.title} placeholder="مثل: ملخص الفصل الثالث" data-testid="input-source-title"/></div><div className="field"><label htmlFor="source-type">نوع المصدر</label><input id="source-type" name="type" defaultValue={item?.type||'ملاحظات شخصية'} data-testid="input-source-type"/></div><div className="field full"><label htmlFor="source-content">النص أو الملاحظات</label><textarea id="source-content" name="content" required defaultValue={item?.content} placeholder="اكتب أو الصق نصًا تريد أن تتعلمه..." data-testid="input-source-content"/></div></div><div className="form-actions"><button className="button button-primary" type="submit" data-testid="button-save-source"><Save size={15}/>{item?'حفظ التعديلات':'إضافة المصدر'}</button><button className="button button-secondary" type="button" onClick={()=>{setEditing(null);setCreating(false)}} data-testid="button-cancel-source">إلغاء</button></div></form>;
  return <div className="content"><PageHeading eyebrow="YOUR MATERIAL, YOUR FOUNDATION" title="مصادري" description="اجمع النصوص التي تثق بها. كل مفهوم وسؤال يبقى مربوطًا بمكانه في المصدر." action={<button className="button button-primary" onClick={()=>{setEditing(null);setCreating(v=>!v)}} data-testid="button-add-source"><Plus size={16}/> مصدر جديد</button>}/>
    {store.sample&&<SampleNote/>}{(creating||editing)&&form(editing)}
    <div className="field" style={{marginBottom:16}}><label htmlFor="source-search">ابحث في مصادرك</label><input id="source-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="عنوان أو كلمة من النص..." data-testid="input-search-sources"/></div>
    {filtered.length?<div className="list-stack">{filtered.map(s=><article className="card source-row" key={s.id} data-testid={`card-source-${s.id}`}><div className="row-icon"><FileText size={18}/></div><div className="row-main"><div className="row-title">{s.title}</div><div className="row-meta"><span className="tag">{s.type}</span><span>{s.content.length} حرفًا</span><span>{store.concepts.filter(c=>c.sourceId===s.id).length} مفاهيم</span></div><p style={{margin:'9px 0 0',fontSize:12,lineHeight:1.8,color:'hsl(var(--muted-foreground))'}}>{s.content.slice(0,150)}{s.content.length>150?'…':''}</p></div><div className="row-actions"><button className="icon-button" aria-label={`تعديل ${s.title}`} onClick={()=>{setCreating(false);setEditing(s)}} data-testid={`button-edit-source-${s.id}`}><Pencil size={16}/></button><button className="icon-button" aria-label={`حذف ${s.title}`} onClick={()=>removeSource(s.id)} data-testid={`button-delete-source-${s.id}`}><Trash2 size={16}/></button></div></article>)}</div>:<Empty title={query?'لم نعثر على مصدر مطابق':'لا توجد مصادر بعد'} copy={query?'جرّب كلمة مختلفة.':'ابدأ بإضافة نص تملكه أو ملاحظات كتبتها بنفسك.'} icon={FileText}/>}
  </div>;
}

function KnowledgePage({store,patch,dropSample}:{store:Store;patch:(k:keyof Store,v:unknown)=>void;dropSample:()=>void}) {
  const [formKind,setFormKind]=useState<'concept'|'relation'|null>(null),[editConcept,setEditConcept]=useState<Concept|null>(null),[editRelation,setEditRelation]=useState<Relation|null>(null),[selected,setSelected]=useState<string|null>(null);
  const saveConcept=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),title=String(f.get('title')).trim(),sourceId=String(f.get('sourceId'));if(!title||!sourceId)return;const item:Concept={id:editConcept?.id||id(),title,sourceId,description:String(f.get('description')).trim(),sourceLocation:String(f.get('sourceLocation')).trim()||'غير محدد',status:String(f.get('status'))};patch('concepts',editConcept?store.concepts.map(c=>c.id===editConcept.id?item:c):[...store.concepts,item]);dropSample();setEditConcept(null);setFormKind(null);};
  const saveRelation=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),from=String(f.get('from')),to=String(f.get('to'));if(!from||!to||from===to)return;const item:Relation={id:editRelation?.id||id(),fromConceptId:from,toConceptId:to,label:String(f.get('label')).trim(),confidence:Number(f.get('confidence')),reviewStatus:String(f.get('reviewStatus'))};patch('relations',editRelation?store.relations.map(r=>r.id===editRelation.id?item:r):[...store.relations,item]);dropSample();setEditRelation(null);setFormKind(null);};
  const deleteConcept=(c:Concept)=>{if(!confirm(`حذف مفهوم «${c.title}»؟`))return;patch('concepts',store.concepts.filter(x=>x.id!==c.id));patch('relations',store.relations.filter(r=>r.fromConceptId!==c.id&&r.toConceptId!==c.id));patch('questions',store.questions.filter(q=>q.conceptId!==c.id));setSelected(null);dropSample();};
  const conceptForm=(item:Concept|null)=><form className="card form-card" onSubmit={saveConcept} data-testid="form-concept"><div className="form-grid"><div className="field"><label htmlFor="concept-title">اسم المفهوم</label><input id="concept-title" name="title" required defaultValue={item?.title} data-testid="input-concept-title"/></div><div className="field"><label htmlFor="concept-source">مرتبط بالمصدر</label><select id="concept-source" name="sourceId" defaultValue={item?.sourceId||store.sources[0]?.id} required data-testid="select-concept-source">{store.sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></div><div className="field full"><label htmlFor="concept-desc">شرحك للمفهوم</label><textarea id="concept-desc" name="description" defaultValue={item?.description} data-testid="input-concept-description"/></div><div className="field"><label htmlFor="concept-loc">موضعه في المصدر</label><input id="concept-loc" name="sourceLocation" defaultValue={item?.sourceLocation} placeholder="فقرة ٢، صفحة ١٠" data-testid="input-concept-location"/></div><div className="field"><label htmlFor="concept-status">حالة المراجعة</label><select id="concept-status" name="status" defaultValue={item?.status||'قيد المراجعة'}><option>قيد المراجعة</option><option>مراجعتي الأولى</option><option>أعود إليه لاحقًا</option></select></div></div><div className="form-actions"><button className="button button-primary" data-testid="button-save-concept">حفظ المفهوم</button><button className="button button-secondary" type="button" onClick={()=>{setFormKind(null);setEditConcept(null)}}>إلغاء</button></div></form>;
  const relationForm=()=><form className="card form-card" onSubmit={saveRelation} data-testid="form-relation"><div className="form-grid"><div className="field"><label>من مفهوم</label><select name="from" defaultValue={editRelation?.fromConceptId||store.concepts[0]?.id}>{store.concepts.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div><div className="field"><label>إلى مفهوم</label><select name="to" defaultValue={editRelation?.toConceptId||store.concepts[1]?.id}>{store.concepts.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div><div className="field"><label>طبيعة العلاقة</label><input name="label" required defaultValue={editRelation?.label} placeholder="يسبب، يسبق، يشبه..." data-testid="input-relation-label"/></div><div className="field"><label>درجة ثقتك بهذه العلاقة: {editRelation?.confidence||70}%</label><input name="confidence" type="range" min="0" max="100" defaultValue={editRelation?.confidence||70} data-testid="input-relation-confidence"/></div><div className="field"><label>حالة المراجعة</label><select name="reviewStatus" defaultValue={editRelation?.reviewStatus||'بحاجة للمراجعة'}><option>بحاجة للمراجعة</option><option>راجعتها بنفسي</option><option>غير متأكد</option></select></div></div><div className="form-actions"><button className="button button-primary" data-testid="button-save-relation">حفظ العلاقة</button><button className="button button-secondary" type="button" onClick={()=>{setFormKind(null);setEditRelation(null)}}>إلغاء</button></div></form>;
  return <div className="content"><PageHeading eyebrow="CONNECT WHAT YOU KNOW" title="خريطة المعرفة" description="ارسم روابطك بنفسك، وراجع قوة العلاقة بدل افتراض صحتها." action={<div style={{display:'flex',gap:8}}><button className="button button-secondary" onClick={()=>{setEditConcept(null);setFormKind('concept')}} data-testid="button-add-concept"><Plus size={15}/> مفهوم</button><button className="button button-primary" disabled={store.concepts.length<2} onClick={()=>{setEditRelation(null);setFormKind('relation')}} data-testid="button-add-relation"><Link2 size={15}/> علاقة</button></div>}/>
    {store.sample&&<SampleNote/>}{formKind==='concept'&&conceptForm(editConcept)}{formKind==='relation'&&relationForm()}
    {!store.sources.length&&<div className="notice" style={{marginBottom:15}}>أضف مصدرًا أولًا حتى تربط المفاهيم بمكانها في النص.</div>}
    <div className="map-grid"><section className="card map-canvas" aria-label="خريطة المفاهيم"><div className="map-nodes">{store.concepts.map((c,i)=><button type="button" onClick={()=>setSelected(selected===c.id?null:c.id)} className="map-node" key={c.id} data-testid={`node-concept-${c.id}`}><div className="map-node-title">{c.title}</div><div className="map-node-caption">{store.sources.find(s=>s.id===c.sourceId)?.title||'مصدر غير متاح'}</div></button>)}{store.concepts.length===0&&<div style={{zIndex:1,textAlign:'center',color:'hsl(var(--muted-foreground))'}}>أضف مفاهيمك لترى الروابط هنا.</div>}</div></section>
    <aside className="card relation-list"><div className="section-title" style={{fontSize:16,marginBottom:8}}>العلاقات</div>{store.relations.length?store.relations.map(r=>{const from=store.concepts.find(c=>c.id===r.fromConceptId),to=store.concepts.find(c=>c.id===r.toConceptId);return <div key={r.id} className="relation-item" data-testid={`relation-${r.id}`}><div style={{fontWeight:600}}>{from?.title||'مفهوم محذوف'} <span style={{color:'hsl(var(--accent))'}}>← {r.label} →</span> {to?.title||'مفهوم محذوف'}</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',color:'hsl(var(--muted-foreground))',fontSize:10,marginTop:6}}><span>{r.confidence}% ثقة · {r.reviewStatus}</span><span className="row-actions"><button className="icon-button" aria-label="تعديل العلاقة" onClick={()=>{setEditRelation(r);setFormKind('relation')}} data-testid={`button-edit-relation-${r.id}`}><Pencil size={14}/></button><button className="icon-button" aria-label="حذف العلاقة" onClick={()=>{if(confirm('حذف هذه العلاقة؟'))patch('relations',store.relations.filter(x=>x.id!==r.id))}} data-testid={`button-delete-relation-${r.id}`}><Trash2 size={14}/></button></span></div></div>}):<p style={{fontSize:12,color:'hsl(var(--muted-foreground))',lineHeight:1.8}}>لا روابط بعد. أضف مفهومين ثم صِف الصلة بينهما.</p>}</aside></div>
    {store.concepts.length>0&&<><div className="section-head"><h2 className="section-title">مفاهيمك</h2><span className="tag">{store.concepts.length} مفاهيم</span></div><div className="list-stack">{store.concepts.map(c=><article className="card concept-row" key={c.id} data-testid={`card-concept-${c.id}`}><div className="row-icon"><Network size={18}/></div><div className="row-main"><div className="row-title">{c.title}</div><div className="row-meta"><span>{c.description||'لم تضف شرحًا بعد'}</span><span>{store.sources.find(s=>s.id===c.sourceId)?.title||'مصدر غير متاح'} · {c.sourceLocation}</span></div></div><span className="tag">{c.status}</span><div className="row-actions"><button className="icon-button" aria-label={`تعديل ${c.title}`} onClick={()=>{setEditConcept(c);setFormKind('concept')}} data-testid={`button-edit-concept-${c.id}`}><Pencil size={15}/></button><button className="icon-button" aria-label={`حذف ${c.title}`} onClick={()=>deleteConcept(c)} data-testid={`button-delete-concept-${c.id}`}><Trash2 size={15}/></button></div></article>)}</div></>}
    {selected&&<div className="notice" style={{marginTop:16}} data-testid="panel-selected-concept">{store.concepts.find(c=>c.id===selected)?.description} — مصدره: {store.sources.find(s=>s.id===store.concepts.find(c=>c.id===selected)?.sourceId)?.title}</div>}
  </div>;
}

function StudyPage({store,patch,dropSample}:{store:Store;patch:(k:keyof Store,v:unknown)=>void;dropSample:()=>void}) {
  const [active,setActive]=useState(false),[index,setIndex]=useState(0),[choice,setChoice]=useState<number|null>(null),[confidence,setConfidence]=useState<number|null>(null),[submitted,setSubmitted]=useState(false),[modeId,setModeId]=useState(store.modes[0]?.id||'');
  const questions=store.questions;const q=questions[index%Math.max(questions.length,1)];const concept=q&&store.concepts.find(c=>c.id===q.conceptId);const source=q&&store.sources.find(s=>s.id===q.sourceId);
  const submit=()=>{if(choice===null||confidence===null||!q)return;const ev:Evidence={id:id(),questionId:q.id,conceptId:q.conceptId,selectedChoice:choice,correct:choice===q.correctChoice,confidence,assisted:false,createdAt:new Date().toISOString()};patch('evidence',[...store.evidence,ev]);dropSample();setSubmitted(true);};
  const next=()=>{setIndex(i=>(i+1)%Math.max(questions.length,1));setChoice(null);setConfidence(null);setSubmitted(false);};
  const reset=()=>{setActive(true);setIndex(0);setChoice(null);setConfidence(null);setSubmitted(false);};
  const mode=store.modes.find(m=>m.id===modeId);
  return <div className="content"><PageHeading eyebrow="RETRIEVAL, NOT RECOGNITION" title="جلسة الاسترجاع" description="فكّر قبل أن تجيب. لا تلميحات ذكية ولا تدخل أثناء تقييمك." action={!active?<button className="button button-primary" onClick={reset} data-testid="button-begin-session"><Brain size={16}/> ابدأ جلسة</button>:<button className="button button-secondary" onClick={()=>setActive(false)} data-testid="button-end-session"><X size={15}/> إنهاء الجلسة</button>}/>
    {store.sample&&<SampleNote/>}
    {!active?<div className="card study-panel"><div className="eyebrow">A QUIET PRACTICE</div><h2 className="section-title" style={{fontSize:24,margin:'13px 0'}}>اختبر ما بقي في ذاكرتك</h2><p className="page-desc" style={{marginBottom:22}}>أسئلة أعددتها من مصادرك. اختر درجة ثقتك بعد الإجابة لنحفظ الاستجابة كدليل فردي، لا كحكم على إتقانك.</p><div className="field" style={{maxWidth:330,marginBottom:18}}><label htmlFor="study-mode">نمط الجلسة</label><select id="study-mode" value={modeId} onChange={e=>setModeId(e.target.value)} data-testid="select-study-mode">{store.modes.map(m=><option key={m.id} value={m.id}>{m.name} · {m.questionCount} أسئلة</option>)}</select></div>{questions.length?<button className="button button-primary" onClick={reset} data-testid="button-session-start-secondary">ابدأ من مصادرك <ArrowLeft size={15}/></button>:<div className="notice">لا توجد أسئلة بعد. أضف سؤالًا من قسم «إدارة أسئلتي» أدناه.</div>}</div>:questions.length&&q?<div className="card study-panel" data-testid={`card-question-${q.id}`}><div className="study-progress"><span>سؤال {index+1} من {mode?.questionCount||questions.length}</span><span>{concept?.title||'مفهوم'}</span></div><div className="progress-track"><div className="progress-fill" style={{width:`${Math.min(((index+1)/(mode?.questionCount||questions.length))*100,100)}%`}}/></div><h2 className="question">{q.prompt}</h2><div className="choice-list" role="radiogroup" aria-label="اختر إجابة">{q.choices.map((c,i)=><button type="button" role="radio" aria-checked={choice===i} className={`choice ${choice===i?'selected':''}`} disabled={submitted} onClick={()=>setChoice(i)} key={i} data-testid={`choice-${i}`}><span className="choice-key">{String.fromCharCode(65+i)}</span>{c}</button>)}</div>
      {!submitted?<><div style={{marginTop:22,fontSize:12,fontWeight:600}}>ما درجة ثقتك بإجابتك؟</div><div className="confidence-options">{[{v:1,l:'أخمن'},{v:2,l:'غير متأكد'},{v:3,l:'واثق'},{v:4,l:'واثق جدًا'}].map(c=><button className={`confidence-chip ${confidence===c.v?'selected':''}`} onClick={()=>setConfidence(c.v)} key={c.v} data-testid={`confidence-${c.v}`}>{c.l}</button>)}</div><button className="button button-primary" style={{marginTop:23}} disabled={choice===null||confidence===null} onClick={submit} data-testid="button-submit-answer">ثبّت إجابتي <Check size={15}/></button></>:<><div className="answer-feedback" role="status" data-testid="status-answer-feedback"><b>{choice===q.correctChoice?'إجابتك تطابق الإجابة المحددة.':'إجابتك مختلفة عن الإجابة المحددة.'}</b><br/>هذا دليل على استجابة واحدة فقط، وليس حكمًا على إتقانك. الإجابة المحددة: {q.choices[q.correctChoice]}<div style={{marginTop:9,display:'flex',gap:8,flexWrap:'wrap'}}><span className="tag">مصدر: {source?.title||'غير متاح'}</span><span className="tag">{q.sourceLocation}</span></div></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:20}}><Link href="/progress" className="text-link" data-testid="link-review-evidence">راجع الدليل المحفوظ</Link><button className="button button-primary" onClick={next} data-testid="button-next-question">السؤال التالي <ArrowLeft size={15}/></button></div></>}</div>:<Empty title="لا توجد أسئلة للتدرب" copy="أضف سؤالًا مرتبطًا بمفهوم ومصدر ثم ابدأ جلسة الاسترجاع." icon={CircleHelp}/>}
    {active&&<button className="button button-quiet" style={{margin:'16px auto',display:'flex'}} onClick={()=>setActive(false)} data-testid="button-session-cancel">إنهاء الجلسة</button>}
    <QuestionManager store={store} patch={patch} dropSample={dropSample}/>
  </div>;
}

function QuestionManager({store,patch,dropSample}:{store:Store;patch:(k:keyof Store,v:unknown)=>void;dropSample:()=>void}) {
  const [open,setOpen]=useState(false),[edit,setEdit]=useState<Question|null>(null);
  const save=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),choices=[String(f.get('a')).trim(),String(f.get('b')).trim(),String(f.get('c')).trim()];const item:Question={id:edit?.id||id(),prompt:String(f.get('prompt')).trim(),choices,correctChoice:Number(f.get('correctChoice')),conceptId:String(f.get('conceptId')),sourceId:String(f.get('sourceId')),sourceLocation:String(f.get('sourceLocation')).trim()};patch('questions',edit?store.questions.map(q=>q.id===edit.id?item:q):[...store.questions,item]);dropSample();setEdit(null);setOpen(false);};
  return <section style={{marginTop:35}}><div className="section-head"><h2 className="section-title">إدارة أسئلتي</h2><button className="button button-secondary" onClick={()=>{setEdit(null);setOpen(v=>!v)}} data-testid="button-add-question"><Plus size={15}/> سؤال جديد</button></div>
    {open&&<form className="card form-card" onSubmit={save} data-testid="form-question"><div className="form-grid"><div className="field full"><label>السؤال</label><input name="prompt" required defaultValue={edit?.prompt} data-testid="input-question-prompt"/></div>{(['a','b','c'] as const).map((key,i)=><div className="field" key={key}><label>الخيار {i+1}</label><input name={key} required defaultValue={edit?.choices[i]} data-testid={`input-question-choice-${i}`}/></div>)}<div className="field"><label>الإجابة المحددة</label><select name="correctChoice" defaultValue={edit?.correctChoice||0}>{['الخيار 1','الخيار 2','الخيار 3'].map((x,i)=><option key={x} value={i}>{x}</option>)}</select></div><div className="field"><label>المفهوم</label><select name="conceptId" required defaultValue={edit?.conceptId||store.concepts[0]?.id}>{store.concepts.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></div><div className="field"><label>المصدر</label><select name="sourceId" required defaultValue={edit?.sourceId||store.sources[0]?.id}>{store.sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></div><div className="field"><label>موضع الإجابة في المصدر</label><input name="sourceLocation" defaultValue={edit?.sourceLocation||'فقرة ١'} data-testid="input-question-location"/></div></div><div className="form-actions"><button className="button button-primary" disabled={!store.sources.length||!store.concepts.length} data-testid="button-save-question">حفظ السؤال</button><button className="button button-secondary" type="button" onClick={()=>setOpen(false)}>إلغاء</button></div></form>}
    {store.questions.length?<div className="list-stack">{store.questions.map(q=><div className="card source-row" key={q.id} data-testid={`card-question-manage-${q.id}`}><div className="row-main"><div className="row-title">{q.prompt}</div><div className="row-meta"><span>{store.concepts.find(c=>c.id===q.conceptId)?.title}</span><span>{store.sources.find(s=>s.id===q.sourceId)?.title} · {q.sourceLocation}</span></div></div><button className="icon-button" aria-label="تعديل السؤال" onClick={()=>{setEdit(q);setOpen(true)}} data-testid={`button-edit-question-${q.id}`}><Pencil size={15}/></button><button className="icon-button" aria-label="حذف السؤال" onClick={()=>{if(confirm('حذف السؤال؟')){patch('questions',store.questions.filter(x=>x.id!==q.id));patch('evidence',store.evidence.filter(x=>x.questionId!==q.id));}}} data-testid={`button-delete-question-${q.id}`}><Trash2 size={15}/></button></div>)}</div>:<Empty title="لا أسئلة بعد" copy="أنشئ سؤالًا من مصادرك لتبدأ تدريبًا بلا مساعدة." icon={CircleHelp}/>}
  </section>;
}

function ProgressPage({store,patch}:{store:Store;patch:(k:keyof Store,v:unknown)=>void}) {
  const total=store.evidence.length,correct=store.evidence.filter(e=>e.correct).length,accuracy=total?Math.round(correct/total*100):0;
  const confGroups=[{label:'ثقة منخفضة',from:1,to:2},{label:'ثقة مرتفعة',from:3,to:4}].map(g=>{const es=store.evidence.filter(e=>e.confidence>=g.from&&e.confidence<=g.to);return {...g,n:es.length,correct:es.filter(e=>e.correct).length};});
  return <div className="content"><PageHeading eyebrow="OBSERVATIONS, NOT VERDICTS" title="أثر التعلّم" description="سجّل ما أجبت عنه وما شعرت به. استجابة واحدة دليل صغير، لا مقياسًا لإتقانك."/>
    <div className="notice" style={{marginBottom:19}} data-testid="notice-evidence-honesty"><ShieldCheck size={15} style={{verticalAlign:'middle',marginLeft:7}}/> نعرض هنا إجاباتك الفردية كما حدثت. لا نستنتج منها إتقانًا أو مستوى ثابتًا.</div>
    <div className="metric-grid"><div className="card metric-card"><div className="eyebrow">RECORDED</div><div className="metric-value" data-testid="value-evidence-total">{total}</div><div className="metric-label">استجابات محفوظة</div></div><div className="card metric-card"><div className="eyebrow">MATCHED ANSWER</div><div className="metric-value">{total?`${accuracy}%`:'—'}</div><div className="metric-label">تطابقت مع الإجابة المحددة، في هذه الاستجابات فقط</div></div><div className="card metric-card"><div className="eyebrow">NO ASSISTANCE</div><div className="metric-value">{total?store.evidence.filter(e=>!e.assisted).length:0}</div><div className="metric-label">إجابات أُجبت دون مساعدة</div></div></div>
    <section className="card chart-card"><h2 className="section-title" style={{fontSize:18}}>الثقة وما أجبت عنه</h2><p className="page-desc" style={{fontSize:12,marginTop:7}}>مقارنة وصفية بين تقديرك لثقتك وتطابق إجاباتك. لا تنبؤات ولا درجات للمفاهيم.</p>{total?confGroups.map(g=><div className="chart-row" key={g.label} data-testid={`chart-confidence-${g.from}`}><span>{g.label}</span><div className="bar-bg"><div className={`bar-fill ${g.from===1?'low':''}`} style={{width:`${g.n?g.correct/g.n*100:0}%`}}/></div><span>{g.n?`${g.correct}/${g.n}`:'لا بيانات'}</span></div>):<div className="empty-state" style={{padding:'26px 10px'}}><div className="empty-mark"><ChartNoAxesColumnIncreasing size={20}/></div><b style={{color:'hsl(var(--foreground))'}}>لا توجد استجابات مسجلة بعد</b><p style={{fontSize:12,margin:'8px 0 0'}}>بعد جلسة الاسترجاع الأولى ستظهر ملاحظاتك هنا.</p></div>}</section>
    <div className="section-head"><h2 className="section-title">سجل الاستجابات</h2><span className="tag">{total} محفوظة</span></div>
    {total?<div className="list-stack">{[...store.evidence].reverse().map(e=>{const q=store.questions.find(x=>x.id===e.questionId),c=store.concepts.find(x=>x.id===e.conceptId);return <article className="card evidence-row" key={e.id} data-testid={`row-evidence-${e.id}`}><div className="row-icon" style={{color:e.correct?'hsl(var(--primary))':'hsl(var(--accent))'}}>{e.correct?<Check size={18}/>:<AlertCircle size={18}/>}</div><div className="row-main"><div className="row-title">{q?.prompt||'سؤال محذوف'}</div><div className="row-meta"><span>{c?.title||'مفهوم محذوف'}</span><span>{new Date(e.createdAt).toLocaleString('ar',{dateStyle:'medium',timeStyle:'short'})}</span></div><div className="row-meta" style={{marginTop:6}}><span>ثقة: {['','أخمن','غير متأكد','واثق','واثق جدًا'][e.confidence]}</span><span>{e.correct?'تطابق مع الإجابة المحددة':'لم تطابق الإجابة المحددة'}</span><span>دون مساعدة</span></div></div></article>})}</div>:null}
  </div>;
}

function SettingsPage({store,patch,onReset,dark,toggleTheme,flash}:{store:Store;patch:(k:keyof Store,v:unknown)=>void;onReset:()=>void;dark:boolean;toggleTheme:()=>void;flash:(s:string)=>void}) {
  const fileRef=useRef<HTMLInputElement>(null),[modeForm,setModeForm]=useState(false);
  const exportData=()=>{const blob=new Blob([JSON.stringify(store,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='itqan-learning-data.json';a.click();URL.revokeObjectURL(url);flash('تم تجهيز نسخة من بياناتك');};
  const importData=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result));if(data?.schema!==1||!Array.isArray(data.sources)||!Array.isArray(data.concepts)||!Array.isArray(data.relations)||!Array.isArray(data.questions)||!Array.isArray(data.evidence)||!Array.isArray(data.modes))throw new Error();setTimeout(()=>{if(confirm('استبدال بيانات المساحة الحالية بالملف؟')){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));window.location.reload();}},0);}catch{flash('تعذر قراءة الملف. تأكد أنه نسخة إتقان صالحة.');}};reader.readAsText(f);e.target.value='';};
  const addMode=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),name=String(f.get('name')).trim();if(!name)return;patch('modes',[...store.modes,{id:id(),name,questionCount:Number(f.get('questionCount')),allowHints:false}]);setModeForm(false);flash('تم حفظ نمط الدراسة');};
  return <div className="content"><PageHeading eyebrow="YOUR SPACE, YOUR RULES" title="إعدادات مساحتك" description="تحكم في طريقة العرض، وأنماط الجلسات، وبياناتك الشخصية."/>
    <section className="card setting-section"><h2 className="setting-title">المظهر</h2><p className="setting-copy">اختر النبرة البصرية التي تناسب وقت دراستك.</p><div className="setting-row"><div><b style={{fontSize:13}}>الوضع الحالي</b><div className="setting-copy" style={{margin:4}}>{dark?'داكن':'فاتح'}</div></div><button className="button button-secondary" onClick={toggleTheme} data-testid="button-theme-setting">{dark?<Sun size={16}/>:<Moon size={16}/>} {dark?'استخدم الفاتح':'استخدم الداكن'}</button></div></section>
    <section className="card setting-section"><h2 className="setting-title">أنماط الدراسة</h2><p className="setting-copy">أنماط ثابتة تنظّم طول الجلسة. جميعها بلا تلميحات، ولا تتدخل في الإجابة.</p><div className="mode-list">{store.modes.map(m=><div className="mode-item" key={m.id} data-testid={`mode-${m.id}`}><span><b>{m.name}</b><span style={{color:'hsl(var(--muted-foreground))'}}> · {m.questionCount} أسئلة · بلا تلميحات</span></span><button className="icon-button" aria-label={`حذف نمط ${m.name}`} onClick={()=>{if(confirm(`حذف نمط «${m.name}»؟`))patch('modes',store.modes.filter(x=>x.id!==m.id))}} data-testid={`button-delete-mode-${m.id}`}><Trash2 size={15}/></button></div>)}</div>{modeForm?<form onSubmit={addMode} className="form-grid" style={{marginTop:14}} data-testid="form-mode"><div className="field"><label>اسم النمط</label><input name="name" required placeholder="مثال: مراجعة سريعة" data-testid="input-mode-name"/></div><div className="field"><label>عدد الأسئلة</label><select name="questionCount" defaultValue="3"><option value="3">٣ أسئلة</option><option value="5">٥ أسئلة</option><option value="8">٨ أسئلة</option></select></div><div className="form-actions"><button className="button button-primary" data-testid="button-save-mode">حفظ النمط</button><button className="button button-secondary" type="button" onClick={()=>setModeForm(false)}>إلغاء</button></div></form>:<button className="button button-secondary" style={{marginTop:14}} onClick={()=>setModeForm(true)} data-testid="button-add-mode"><Plus size={15}/> نمط مخصص</button>}</section>
    <section className="card setting-section"><h2 className="setting-title">بياناتك محلية</h2><p className="setting-copy">المصادر والمفاهيم والإجابات تبقى في تخزين المتصفح على هذا الجهاز. لا نرسلها إلى خادم.</p><div className="notice" style={{marginBottom:15}}><ShieldCheck size={15} style={{verticalAlign:'middle',marginLeft:7}}/> احتفظ بنسخة تصدير إذا أردت نقل بياناتك أو حفظها خارج هذا المتصفح.</div><div style={{display:'flex',gap:9,flexWrap:'wrap'}}><button className="button button-primary" onClick={exportData} data-testid="button-export-data"><ArrowDownToLine size={15}/> تصدير بياناتي</button><button className="button button-secondary" onClick={()=>fileRef.current?.click()} data-testid="button-import-data"><Upload size={15}/> استيراد نسخة</button><input ref={fileRef} type="file" accept="application/json,.json" style={{display:'none'}} onChange={importData} data-testid="input-import-file"/></div><div className="setting-row" style={{marginTop:15}}><div><b style={{fontSize:13}}>إعادة ضبط المساحة</b><div className="setting-copy" style={{margin:'4px 0 0'}}>يحذف بياناتك المحلية ويعيد أمثلة البداية.</div></div><button className="button button-danger" onClick={onReset} data-testid="button-reset-data"><RotateCcw size={15}/> إعادة الضبط</button></div></section>
  </div>;
}

function App() {
  return <WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/,'')}><WorkspaceApp/></WouterRouter>;
}

export default App;